[2024-07-25T15:59:33.187+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:59:33.227+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_data_processing_pipeline.load_to_bucket manual__2024-07-25T15:58:10.182137+00:00 [queued]>
[2024-07-25T15:59:33.239+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_data_processing_pipeline.load_to_bucket manual__2024-07-25T15:58:10.182137+00:00 [queued]>
[2024-07-25T15:59:33.239+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:59:33.257+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_bucket> on 2024-07-25 15:58:10.182137+00:00
[2024-07-25T15:59:33.264+0000] {standard_task_runner.py:64} INFO - Started process 222 to run task
[2024-07-25T15:59:33.269+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_data_processing_pipeline', 'load_to_bucket', 'manual__2024-07-25T15:58:10.182137+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/raw_data_processing_pipeline.py', '--cfg-path', '/tmp/tmp6o3j5cxl']
[2024-07-25T15:59:33.271+0000] {standard_task_runner.py:91} INFO - Job 154: Subtask load_to_bucket
[2024-07-25T15:59:33.363+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_data_processing_pipeline.load_to_bucket manual__2024-07-25T15:58:10.182137+00:00 [running]> on host 3856c9d2f42a
[2024-07-25T15:59:33.527+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='raw_data_processing_pipeline' AIRFLOW_CTX_TASK_ID='load_to_bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T15:58:10.182137+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-25T15:58:10.182137+00:00'
[2024-07-25T15:59:33.529+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:59:33.563+0000] {logging_mixin.py:188} WARNING - An error occurred while uploading files: [Errno 2] No such file or directory: 'gsutil'
[2024-07-25T15:59:33.564+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:59:33.565+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:59:33.587+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=raw_data_processing_pipeline, task_id=load_to_bucket, run_id=manual__2024-07-25T15:58:10.182137+00:00, execution_date=20240725T155810, start_date=20240725T155933, end_date=20240725T155933
[2024-07-25T15:59:33.642+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:59:33.677+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:59:33.680+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
