[2024-07-25T16:04:56.192+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T16:04:56.233+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_data_processing_pipeline.load_to_bucket scheduled__2024-07-25T15:01:00+00:00 [queued]>
[2024-07-25T16:04:56.245+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_data_processing_pipeline.load_to_bucket scheduled__2024-07-25T15:01:00+00:00 [queued]>
[2024-07-25T16:04:56.245+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T16:04:56.264+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_bucket> on 2024-07-25 15:01:00+00:00
[2024-07-25T16:04:56.270+0000] {standard_task_runner.py:64} INFO - Started process 214 to run task
[2024-07-25T16:04:56.276+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_data_processing_pipeline', 'load_to_bucket', 'scheduled__2024-07-25T15:01:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/raw_data_processing_pipeline.py', '--cfg-path', '/tmp/tmpkck8qm9m']
[2024-07-25T16:04:56.278+0000] {standard_task_runner.py:91} INFO - Job 159: Subtask load_to_bucket
[2024-07-25T16:04:56.367+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_data_processing_pipeline.load_to_bucket scheduled__2024-07-25T15:01:00+00:00 [running]> on host e4392ddf2110
[2024-07-25T16:04:56.525+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='raw_data_processing_pipeline' AIRFLOW_CTX_TASK_ID='load_to_bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T15:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-25T15:01:00+00:00'
[2024-07-25T16:04:56.526+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T16:04:56.558+0000] {logging_mixin.py:188} WARNING - An error occurred while uploading files: [Errno 2] No such file or directory: 'gsutil'
[2024-07-25T16:04:56.559+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T16:04:56.560+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T16:04:56.581+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=raw_data_processing_pipeline, task_id=load_to_bucket, run_id=scheduled__2024-07-25T15:01:00+00:00, execution_date=20240725T150100, start_date=20240725T160456, end_date=20240725T160456
[2024-07-25T16:04:56.608+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T16:04:56.641+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T16:04:56.643+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
