[2024-07-25T15:51:34.830+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-25T15:51:34.871+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_data_processing_pipeline.load_to_bucket manual__2024-07-25T15:49:38.318781+00:00 [queued]>
[2024-07-25T15:51:34.882+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_data_processing_pipeline.load_to_bucket manual__2024-07-25T15:49:38.318781+00:00 [queued]>
[2024-07-25T15:51:34.882+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-25T15:51:34.900+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_bucket> on 2024-07-25 15:49:38.318781+00:00
[2024-07-25T15:51:34.906+0000] {standard_task_runner.py:64} INFO - Started process 246 to run task
[2024-07-25T15:51:34.911+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_data_processing_pipeline', 'load_to_bucket', 'manual__2024-07-25T15:49:38.318781+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/raw_data_processing_pipeline.py', '--cfg-path', '/tmp/tmpy_zc80jb']
[2024-07-25T15:51:34.914+0000] {standard_task_runner.py:91} INFO - Job 149: Subtask load_to_bucket
[2024-07-25T15:51:35.001+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_data_processing_pipeline.load_to_bucket manual__2024-07-25T15:49:38.318781+00:00 [running]> on host dfb2dd86b1b2
[2024-07-25T15:51:35.152+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='raw_data_processing_pipeline' AIRFLOW_CTX_TASK_ID='load_to_bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-07-25T15:49:38.318781+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-25T15:49:38.318781+00:00'
[2024-07-25T15:51:35.154+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-25T15:51:35.183+0000] {logging_mixin.py:188} WARNING - An error occurred while uploading files: [Errno 2] No such file or directory: 'gsutil'
[2024-07-25T15:51:35.184+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-25T15:51:35.185+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-25T15:51:35.209+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=raw_data_processing_pipeline, task_id=load_to_bucket, run_id=manual__2024-07-25T15:49:38.318781+00:00, execution_date=20240725T154938, start_date=20240725T155134, end_date=20240725T155135
[2024-07-25T15:51:35.244+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-25T15:51:35.281+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-25T15:51:35.284+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
