[2024-07-24T12:01:05.423+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T12:01:05.464+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_data_processing_pipeline.themuse_api_call scheduled__2024-07-24T11:01:00+00:00 [queued]>
[2024-07-24T12:01:05.477+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_data_processing_pipeline.themuse_api_call scheduled__2024-07-24T11:01:00+00:00 [queued]>
[2024-07-24T12:01:05.477+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T12:01:05.496+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): themuse_api_call> on 2024-07-24 11:01:00+00:00
[2024-07-24T12:01:05.504+0000] {standard_task_runner.py:64} INFO - Started process 137363 to run task
[2024-07-24T12:01:05.509+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'raw_data_processing_pipeline', 'themuse_api_call', 'scheduled__2024-07-24T11:01:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/raw_data_processing_pipeline.py', '--cfg-path', '/tmp/tmp7fr3uzj2']
[2024-07-24T12:01:05.511+0000] {standard_task_runner.py:91} INFO - Job 115: Subtask themuse_api_call
[2024-07-24T12:01:05.602+0000] {task_command.py:426} INFO - Running <TaskInstance: raw_data_processing_pipeline.themuse_api_call scheduled__2024-07-24T11:01:00+00:00 [running]> on host 3f3ef3b72f68
[2024-07-24T12:01:05.761+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='raw_data_processing_pipeline' AIRFLOW_CTX_TASK_ID='themuse_api_call' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T11:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T11:01:00+00:00'
[2024-07-24T12:01:05.763+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T12:01:13.476+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_jobs_part_1.csv': 200 jobs
[2024-07-24T12:01:20.848+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_jobs_part_2.csv': 200 jobs
[2024-07-24T12:01:26.394+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_jobs_part_3.csv': 200 jobs
[2024-07-24T12:01:31.665+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_jobs_part_4.csv': 200 jobs
[2024-07-24T12:01:37.448+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_jobs_part_5.csv': 200 jobs
[2024-07-24T12:03:53.172+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_jobs_part_6.csv': 200 jobs
[2024-07-24T12:03:57.124+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_jobs_part_7.csv': 200 jobs
[2024-07-24T12:04:02.496+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_jobs_part_8.csv': 200 jobs
[2024-07-24T12:04:08.143+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_jobs_part_9.csv': 200 jobs
[2024-07-24T12:04:13.494+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_jobs_part_10.csv': 200 jobs
[2024-07-24T12:04:14.062+0000] {logging_mixin.py:188} INFO - Error 400: Value `page` is too high
[2024-07-24T12:04:17.334+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_companies_part_1.csv': 200 companies
[2024-07-24T12:04:20.410+0000] {logging_mixin.py:188} INFO - Saved to 'data/raw/themuse_companies_part_2.csv': 200 companies
[2024-07-24T12:06:01.248+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T12:06:01.250+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/freeprise-matchmaker-BsnH11MF-py3.8/lib/python3.8/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/freeprise-matchmaker-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/freeprise-matchmaker-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/root/.cache/pypoetry/virtualenvs/freeprise-matchmaker-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/freeprise-matchmaker-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/root/.cache/pypoetry/virtualenvs/freeprise-matchmaker-BsnH11MF-py3.8/lib/python3.8/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/app/airflow/api_calls/themuse_api_call.py", line 159, in themuse_api_call
    fetch_all_companies()
  File "/app/airflow/api_calls/themuse_api_call.py", line 124, in fetch_all_companies
    companies_data, headers = fetch_companies(page=page, descending=descending, industry=industry, size=size, location=location)
  File "/app/airflow/api_calls/themuse_api_call.py", line 73, in fetch_companies
    error_data = response.json()
  File "/root/.cache/pypoetry/virtualenvs/freeprise-matchmaker-BsnH11MF-py3.8/lib/python3.8/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2024-07-24T12:06:01.272+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=raw_data_processing_pipeline, task_id=themuse_api_call, run_id=scheduled__2024-07-24T11:01:00+00:00, execution_date=20240724T110100, start_date=20240724T120105, end_date=20240724T120601
[2024-07-24T12:06:01.290+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 115 for task themuse_api_call (Expecting value: line 1 column 1 (char 0); 137363)
[2024-07-24T12:06:01.320+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T12:06:01.361+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T12:06:01.367+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
